server:
  port: 8088

spring:
  application:
    name: social-connect
  datasource:
    url: jdbc:mysql://localhost:3306/socialConnect?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  elasticsearch:
    host: ${ES_HOST:localhost}
    port: ${ES_PORT:9200}
    username: ${ES_USERNAME:}
    password: ${ES_PASSWORD:}

  minio:
    url: http://${MINIO_HOST:localhost}:9000
    bucket: ${MINIO_BUCKET:sn-file-items}
    access-key: ${MINIO_ACCESS_KEY:ROOTUSER}
    secret-key: ${MINIO_SECRET_KEY:CHANGEME123}

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
